apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjoge30sCiAgICAiYXV0aCI6ICJiV2RoYkdsdGRXeHNhVzQ2WjJod1gwVnJXbmhDWmxVNVMxWTVRazVzYTFOMmVYWkdkVmx5YVRKRmFISlhlVE4xYWtKa1R3PT0iCgkiY3JlZEhlbHBlcnMiOiB7CgkJImRvY2tlci1ob3N0ZWQuYXJ0aWZhY3RvcnkudGNzYmFuay5ydSI6ICJhcnRpZmFjdG9yeSIsCgkJImRvY2tlci1wcm94eS5hcnRpZmFjdG9yeS50Y3NiYW5rLnJ1IjogImFydGlmYWN0b3J5IgoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9Cg==
type: kubernetes.io/dockerconfigjson
