apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjoge30sCiAgICAiYXV0aCI6ICJiV2RoYkdsdGRXeHNhVzQ2WjJod1gwVnJXbmhDWmxVNVMxWTVRazVzYTFOMmVYWkdkVmx5YVRKRmFISlhlVE4xYWtKa1R3PT0iLAoJImNyZWRIZWxwZXJzIjogewoJCSJkb2NrZXItaG9zdGVkLmFydGlmYWN0b3J5LnRjc2JhbmsucnUiOiAiYXJ0aWZhY3RvcnkiLAoJCSJkb2NrZXItcHJveHkuYXJ0aWZhY3RvcnkudGNzYmFuay5ydSI6ICJhcnRpZmFjdG9yeSIKCX0sCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
type: kubernetes.io/dockerconfigjson
